### ISSUE TITLE
text color to change when the bar turns orange for debugging

### ISSUE THREAD

**Issue by nicolapreda** [Senpai-10/discord-vscode-theme#1]
Hi, 
I noticed that the color of the text in the orange bar during debugging becomes difficult to read, would you be able to change it and put it white? Thank you

![image](https://user-images.githubusercontent.com/64780086/121141496-4b7c6000-c83b-11eb-9d8b-dae4ccb2b039.png)

**Comment by mesalilac** [comment]
i made a new release, now update the extension
